In [1]:
import numpy as np
import torch.nn as nn
import torch

In [2]:
def softmax1(x):
    return np.exp(x)/np.sum(np.exp(x))

x = np.array([2, 3, 4, 2.2, 3.5])
output = softmax1(x)
print("softmax  outputs:", output)

softmax  outputs: [0.05948688 0.1617021  0.43955189 0.07265744 0.2666017 ]


In [3]:
y = torch.tensor(x)

In [4]:
output = torch.softmax(y, dim=0)
output

tensor([0.0595, 0.1617, 0.4396, 0.0727, 0.2666], dtype=torch.float64)

In [7]:
torch.sigmoid(y)

tensor([0.8808, 0.9526, 0.9820, 0.9002, 0.9707], dtype=torch.float64)

In [8]:
torch.relu(y)

tensor([2.0000, 3.0000, 4.0000, 2.2000, 3.5000], dtype=torch.float64)

In [13]:
torch.tanh(y)

tensor([0.9640, 0.9951, 0.9993, 0.9757, 0.9982], dtype=torch.float64)