In [16]:
import numpy as np

In [18]:
# activation function

def sigmoid(x):
    return (1/(1+np.exp(-x)))

In [19]:
def s_der(x):
    return x*(1-x)

In [20]:
#inputs
input = np.array(
    [
        [1,0,1],
        [1,1,1],
        [0,1,1],
        [0,0,1]
    ]
)

In [21]:
t_output = np.array([[1,1,0,0]]).T
print(t_output)

[[1]
 [1]
 [0]
 [0]]


In [22]:
weights = 2*np.random.random((3,1))-1
weights

array([[ 0.43378483],
       [-0.4737195 ],
       [-0.54985858]])

In [23]:
for i in range(10):
  output = sigmoid(np.dot(input, weights))
  error = t_output - output
  adjustments = error * s_der(output)
  weights += np.dot(input.T, adjustments)
np.round(output)

array([[1.],
       [1.],
       [0.],
       [0.]])

In [ ]:
output

array([[0.71403559],
       [0.54143429],
       [0.34679038],
       [0.52891015]])

In [ ]:
np.round(output)

array([[1.],
       [1.],
       [0.],
       [1.]])